# Введение в обработку текста на естественном языке

Материалы:
* Макрушин С.В. Лекция 9: Введение в обработку текста на естественном языке\
* https://realpython.com/nltk-nlp-python/
* https://scikit-learn.org/stable/modules/feature_extraction.html

## Задачи для совместного разбора

In [2]:
pip install pymorphy2

  Obtaining dependency information for pymorphy2 from https://files.pythonhosted.org/packages/07/57/b2ff2fae3376d4f3c697b9886b64a54b476e1a332c67eee9f88e7f1ae8c9/pymorphy2-0.9.1-py3-none-any.whl.metadata
  Obtaining dependency information for dawg-python>=0.7.1 from https://files.pythonhosted.org/packages/6a/84/ff1ce2071d4c650ec85745766c0047ccc3b5036f1d03559fd46bb38b5eeb/DAWG_Python-0.7.2-py2.py3-none-any.whl.metadata
  Obtaining dependency information for pymorphy2-dicts-ru<3.0,>=2.4 from https://files.pythonhosted.org/packages/3a/79/bea0021eeb7eeefde22ef9e96badf174068a2dd20264b9a378f2be1cdd9e/pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl.metadata
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using cached pymorphy2-0.9.1-py3-none-any.whl (55 kB)
Using cached DAWG_Python-0.7.2-py2.py3-none-any.whl (11 kB)
Using cached pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl 

In [10]:
pip install pymystem3

  Obtaining dependency information for pymystem3 from https://files.pythonhosted.org/packages/00/8c/98b43c5822620458704e187a1666616c1e21a846ede8ffda493aabe11207/pymystem3-0.2.0-py3-none-any.whl.metadata
Note: you may need to restart the kernel to use updated packages.


In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import pymorphy2
import re
import numpy as np
import pandas as pd
import random

1. Считайте слова из файла `litw-win.txt` и запишите их в список `words`. В заданном предложении исправьте все опечатки, заменив слова с опечатками на ближайшие (в смысле расстояния Левенштейна) к ним слова из списка `words`. Считайте, что в слове есть опечатка, если данное слово не содержится в списке `words`. 

In [4]:
text = '''с велечайшим усилием выбравшись из потока убегающих людей Кутузов со свитой уменьшевшейся вдвое поехал на звуки выстрелов русских орудий'''

2. Разбейте текст из формулировки задания 1 на слова; проведите стемминг и лемматизацию слов.

In [4]:
text = 'Считайте слова из файла litw-win.txt и запишите их в список words. В заданном предложении исправьте все опечатки, заменив слова с опечатками на ближайшие (в смысле расстояния Левенштейна) к ним слова из списка words. Считайте, что в слове есть опечатка, если данное слово не содержится в списке words.'


def tknz(data):
   return re.findall(r'[а-яА-яЁёa-zA-z]+', data)


res = tknz(text)
res

['Считайте',
 'слова',
 'из',
 'файла',
 'litw',
 'win',
 'txt',
 'и',
 'запишите',
 'их',
 'в',
 'список',
 'words',
 'В',
 'заданном',
 'предложении',
 'исправьте',
 'все',
 'опечатки',
 'заменив',
 'слова',
 'с',
 'опечатками',
 'на',
 'ближайшие',
 'в',
 'смысле',
 'расстояния',
 'Левенштейна',
 'к',
 'ним',
 'слова',
 'из',
 'списка',
 'words',
 'Считайте',
 'что',
 'в',
 'слове',
 'есть',
 'опечатка',
 'если',
 'данное',
 'слово',
 'не',
 'содержится',
 'в',
 'списке',
 'words']

In [1]:
from nltk.stem import SnowballStemmer, WordNetLemmatizer

In [6]:
stemmer = SnowballStemmer("russian")
stemmed_words = [stemmer.stem(word) for word in res]

print(stemmed_words)

['счита', 'слов', 'из', 'файл', 'litw', 'win', 'txt', 'и', 'запиш', 'их', 'в', 'список', 'words', 'в', 'зада', 'предложен', 'исправьт', 'все', 'опечатк', 'замен', 'слов', 'с', 'опечатк', 'на', 'ближайш', 'в', 'смысл', 'расстоян', 'левенштейн', 'к', 'ним', 'слов', 'из', 'списк', 'words', 'счита', 'что', 'в', 'слов', 'ест', 'опечатк', 'есл', 'дан', 'слов', 'не', 'содерж', 'в', 'списк', 'words']


In [8]:
lemmatizer = WordNetLemmatizer()
l = [lemmatizer.lemmatize(word) for word in res]

l

['Считайте',
 'слова',
 'из',
 'файла',
 'litw',
 'win',
 'txt',
 'и',
 'запишите',
 'их',
 'в',
 'список',
 'word',
 'В',
 'заданном',
 'предложении',
 'исправьте',
 'все',
 'опечатки',
 'заменив',
 'слова',
 'с',
 'опечатками',
 'на',
 'ближайшие',
 'в',
 'смысле',
 'расстояния',
 'Левенштейна',
 'к',
 'ним',
 'слова',
 'из',
 'списка',
 'word',
 'Считайте',
 'что',
 'в',
 'слове',
 'есть',
 'опечатка',
 'если',
 'данное',
 'слово',
 'не',
 'содержится',
 'в',
 'списке',
 'word']

In [10]:
from pymystem3 import Mystem

In [11]:
Mystem().lemmatize(text)

['считать',
 ' ',
 'слово',
 ' ',
 'из',
 ' ',
 'файл',
 ' ',
 'litw',
 '-',
 'win',
 '.',
 'txt',
 ' ',
 'и',
 ' ',
 'записывать',
 ' ',
 'они',
 ' ',
 'в',
 ' ',
 'список',
 ' ',
 'words',
 '. ',
 'в',
 ' ',
 'заданный',
 ' ',
 'предложение',
 ' ',
 'исправлять',
 ' ',
 'весь',
 ' ',
 'опечатка',
 ', ',
 'заменять',
 ' ',
 'слово',
 ' ',
 'с',
 ' ',
 'опечатка',
 ' ',
 'на',
 ' ',
 'близкий',
 ' (',
 'в',
 ' ',
 'смысл',
 ' ',
 'расстояние',
 ' ',
 'левенштейн',
 ') ',
 'к',
 ' ',
 'они',
 ' ',
 'слово',
 ' ',
 'из',
 ' ',
 'список',
 ' ',
 'words',
 '. ',
 'считать',
 ', ',
 'что',
 ' ',
 'в',
 ' ',
 'слово',
 ' ',
 'быть',
 ' ',
 'опечатка',
 ', ',
 'если',
 ' ',
 'данный',
 ' ',
 'слово',
 ' ',
 'не',
 ' ',
 'содержаться',
 ' ',
 'в',
 ' ',
 'список',
 ' ',
 'words',
 '.',
 '\n']

In [11]:
from pymystem3 import Mystem

def lemmatize_sentence(text):
    lemmas = Mystem().lemmatize(text)
    return "".join(lemmas).strip()

lemmatize_sentence(text)

Installing mystem to C:\Users\Elizabeth/.local/bin\mystem.exe from http://download.cdn.yandex.net/mystem/mystem-3.1-win-64bit.zip


'считать слово из файл litw-win.txt и записывать они в список words. в заданный предложение исправлять весь опечатка, заменять слово с опечатка на близкий (в смысл расстояние левенштейн) к они слово из список words. считать, что в слово быть опечатка, если данный слово не содержаться в список words.'

3. Преобразуйте предложения из формулировки задания 1 в векторы при помощи `CountVectorizer`.

In [259]:
from nltk.tokenize import sent_tokenize

In [258]:
text = 'Считайте слова из файла litw-win.txt и запишите их в список words. В заданном предложении исправьте все опечатки, заменив слова с опечатками на ближайшие (в смысле расстояния Левенштейна) к ним слова из списка words. Считайте, что в слове есть опечатка, если данное слово не содержится в списке words.'

In [261]:
task1 = sent_tokenize(text)

In [262]:
cv = CountVectorizer()

task1_cv = cv.fit_transform(task1)

In [263]:
task1_cv.toarray()

array([[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=int64)

## Лабораторная работа 9

### Расстояние редактирования

1.1 Загрузите предобработанные описания рецептов из файла `preprocessed_descriptions.csv`. Получите набор уникальных слов `words`, содержащихся в текстах описаний рецептов (воспользуйтесь `word_tokenize` из `nltk`). 

In [13]:
from nltk.tokenize import word_tokenize

In [14]:
p_d = pd.read_csv('preprocessed_descriptions.csv')

In [15]:
p_d

name  \
0             george s at the cove  black bean soup   
1                healthy for them  yogurt popsicles   
2                      i can t believe it s spinach   
3                              italian  gut busters   
4          love is in the air  beef fondue   sauces   
...                                             ...   
29995  zurie s holey rustic olive and cheddar bread   
29996          zwetschgenkuchen  bavarian plum cake   
29997   zwiebelkuchen   southwest german onion cake   
29998                                   zydeco soup   
29999        cookies by design   cookies on a stick   

                               preprocessed_descriptions  
0      an original recipe created by chef scott meska...  
1      my children and their friends ask for my homem...  
2                  these were so go it surprised even me  
3      my sisterinlaw made these for us at a family g...  
4      i think a fondue is a very romantic casual din...  
...                                                  ...  
29995  this is based on a french recipe but i changed...  
29996  this is a traditional fresh plum cake thought ...  
29997  this is a traditional late summer early fall s...  
29998  this is a delicious soup that i originally fou...  
29999  ive heard of the cookies by design company but...  

[30000 rows x 2 columns]

In [16]:
words = [word_tokenize(str(i)) for i in p_d['preprocessed_descriptions']]

In [17]:
words = []

for i in p_d['preprocessed_descriptions']:
    words += word_tokenize(str(i))
    
words = list(set(words))

In [115]:
len(words)

32868

1.2 Сгенерируйте 5 пар случайно выбранных слов и посчитайте между ними расстояние редактирования.

In [18]:
para = [[random.choice(list(words)), random.choice(list(words))] for _ in range(5)]

In [19]:
para

[['unsweetened', 'crop'],
 ['beleive', 'sipping'],
 ['plumped', 'multi'],
 ['4045', 'scalding'],
 ['sisterinlaw', 'pierced']]

In [21]:
from nltk.metrics.distance import edit_distance

In [22]:
for i in para:
    print(i, edit_distance(i[0], i[1], substitution_cost=2))

['unsweetened', 'crop'] 15
['beleive', 'sipping'] 12
['plumped', 'multi'] 10
['4045', 'scalding'] 12
['sisterinlaw', 'pierced'] 12


In [24]:
import nltk

In [26]:
for i in para:
    print(i, nltk.edit_distance(i[0], i[1], substitution_cost=2))

['unsweetened', 'crop'] 15
['beleive', 'sipping'] 12
['plumped', 'multi'] 10
['4045', 'scalding'] 12
['sisterinlaw', 'pierced'] 12


1.3 Напишите функцию, которая для заданного слова `word` возвращает `k` ближайших к нему слов из списка `words` (близость слов измеряется с помощью расстояния Левенштейна)

In [254]:
def Levenstein(word, ww, k):
    r = {}
    for w in ww:
        if w != word:
            r[w] = edit_distance(word, w, substitution_cost=2)
    srt = sorted(r.items(), key=lambda item: item[1])
    r = {k: v for k, v in srt}
    return [srt[i][0] for i in range(k)]

In [257]:
W = 'popsicles'

Levenstein(W, words, 3)

['popsicle', 'potpies', 'piles']

### Стемминг, лемматизация

2.1 На основе результатов 1.1 создайте `pd.DataFrame` со столбцами: 
    * word
    * stemmed_word 
    * normalized_word 

Столбец `word` укажите в качестве индекса. 

Для стемминга воспользуйтесь `SnowballStemmer`, для нормализации слов - `WordNetLemmatizer`. Сравните результаты стемминга и лемматизации.

In [27]:
st = [stemmer.stem(i) for i in words]

In [28]:
nr = [lemmatizer.lemmatize(i) for i in words]

In [29]:
df = pd.DataFrame({'word': words, 'stemmed_word': st, 'normalized_word': nr})
df.set_index('word', inplace=True)
df

stemmed_word  normalized_word
word                                             
sealer                    sealer           sealer
226422                    226422           226422
straightforward  straightforward  straightforward
vegetablesyour    vegetablesyour   vegetablesyour
promiscuous          promiscuous      promiscuous
...                          ...              ...
greatnieces          greatnieces      greatnieces
migrants                migrants          migrant
pam                          pam              pam
connoisseur          connoisseur      connoisseur
quenches                quenches         quenches

[32868 rows x 2 columns]

2.2. Удалите стоп-слова из описаний рецептов. Какую долю об общего количества слов составляли стоп-слова? Сравните топ-10 самых часто употребляемых слов до и после удаления стоп-слов.

In [141]:
import nltk

In [142]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Elizabeth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [31]:
from nltk.corpus import stopwords

In [145]:
en_stop_words = stopwords.words('english')

In [151]:
wrds = []

for i in p_d['preprocessed_descriptions']:
    wrds += word_tokenize(str(i))

In [171]:
non_stop = [i for i in wrds if i not in en_stop_words]

In [172]:
(len(wrds) - len(non_stop))/len(wrds)

0.4564649471672189

In [168]:
def count_frec(lst, k=10):
    dct = {}
    for i in lst:
        dct[i] = dct[i] + 1 if i in dct else 1
    dct = {x: dct[x] for x in sorted(dct.keys(), key=lambda ele: dct[ele], reverse=True)}
    return list(dct.keys())[0:k]

In [173]:
count_frec(wrds), count_frec(non_stop)

(['the', 'a', 'and', 'this', 'i', 'to', 'is', 'it', 'of', 'for'],
 ['recipe',
  'make',
  'time',
  'use',
  'great',
  'like',
  'easy',
  'one',
  'made',
  'good'])

### Векторное представление текста

3.1 Выберите случайным образом 5 рецептов из набора данных. Представьте описание каждого рецепта в виде числового вектора при помощи `TfidfVectorizer`

In [35]:
from sklearn.feature_extraction.text import (CountVectorizer, TfidfVectorizer)

In [38]:
sample = p_d.sample(n=5)
sample['preprocessed_descriptions']

11055    this is a combination of the best elements of ...
12225    this is the recipe ive used for years to make ...
26384    mocktails are nonalcoholic drinks this is a gr...
16719    use 1 or 2 tablespoons for an authentic madras...
7952     i love cranberries and orange together and thi...
Name: preprocessed_descriptions, dtype: object

In [39]:
tv = TfidfVectorizer()

samp_tv = tv.fit_transform(sample['preprocessed_descriptions'])

In [47]:
sa = samp_tv.toarray()
sa

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.11571206, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.17277892, 0.        ,
        0.17277892, 0.        , 0.        , 0.        , 0.        ,
        0.17277892, 0.17277892, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17277892, 0.17277892, 0.        , 0.        ,
        0.17277892, 0.17277892, 0.        , 0.        , 0.17277892,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17277892, 0.17277892, 0.        , 0.17277892,
        0.17277892, 0.09734063, 0.        , 0.13939694, 0.13939694,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.17277892, 0.        , 0.        , 0.        , 0.        ,
        0.17277892, 0.        , 0.        , 0.17277892, 0.41819083,
        0.        , 0.        , 0.        , 0.  

3.2 Вычислите близость между каждой парой рецептов, выбранных в задании 3.1, используя косинусное расстояние (`scipy.spatial.distance.cosine`) Результаты оформите в виде таблицы `pd.DataFrame`. В качестве названий строк и столбцов используйте названия рецептов.

In [41]:
import scipy

In [42]:
similarity = samp_tv * samp_tv.T
similarity.toarray()

array([[1.        , 0.27299176, 0.03454028, 0.        , 0.093111  ],
       [0.27299176, 1.        , 0.04849036, 0.02736766, 0.0923047 ],
       [0.03454028, 0.04849036, 1.        , 0.05175345, 0.07032919],
       [0.        , 0.02736766, 0.05175345, 1.        , 0.        ],
       [0.093111  , 0.0923047 , 0.07032919, 0.        , 1.        ]])

In [43]:
recipe_names = sample['name'].to_numpy()

distance_cosine = pd.DataFrame({recipe_names[i]: similarity.toarray()[i] for i in range(5)}, index=recipe_names)

In [44]:
distance_cosine

fish tacos with herb yogurt  \
fish tacos with herb yogurt                     1.000000   
golden fried cornbread                          0.272992   
sunset cooler  mocktail                         0.034540   
madras curry paste                              0.000000   
cranberry orange scones                         0.093111   

                             golden fried cornbread  sunset cooler  mocktail  \
fish tacos with herb yogurt                0.272992                 0.034540   
golden fried cornbread                     1.000000                 0.048490   
sunset cooler  mocktail                    0.048490                 1.000000   
madras curry paste                         0.027368                 0.051753   
cranberry orange scones                    0.092305                 0.070329   

                             madras curry paste  cranberry orange scones  
fish tacos with herb yogurt            0.000000                 0.093111  
golden fried cornbread                 0.027368                 0.092305  
sunset cooler  mocktail                0.051753                 0.070329  
madras curry paste                     1.000000                 0.000000  
cranberry orange scones                0.000000                 1.000000

In [48]:
distances = []

for i in range(5):
    dist = []
    for j in range(5):
        dist.append(scipy.spatial.distance.cosine(sa[i], sa[j]))
    distances.append(dist)

In [54]:
distances = np.array(distances)
distances

array([[0.        , 0.72700824, 0.96545972, 1.        , 0.906889  ],
       [0.72700824, 0.        , 0.95150964, 0.97263234, 0.9076953 ],
       [0.96545972, 0.95150964, 0.        , 0.94824655, 0.92967081],
       [1.        , 0.97263234, 0.94824655, 0.        , 1.        ],
       [0.906889  , 0.9076953 , 0.92967081, 1.        , 0.        ]])

In [56]:
dc = pd.DataFrame({recipe_names[i]: 1-distances[i] for i in range(5)}, index=recipe_names)
dc

fish tacos with herb yogurt  \
fish tacos with herb yogurt                     1.000000   
golden fried cornbread                          0.272992   
sunset cooler  mocktail                         0.034540   
madras curry paste                              0.000000   
cranberry orange scones                         0.093111   

                             golden fried cornbread  sunset cooler  mocktail  \
fish tacos with herb yogurt                0.272992                 0.034540   
golden fried cornbread                     1.000000                 0.048490   
sunset cooler  mocktail                    0.048490                 1.000000   
madras curry paste                         0.027368                 0.051753   
cranberry orange scones                    0.092305                 0.070329   

                             madras curry paste  cranberry orange scones  
fish tacos with herb yogurt            0.000000                 0.093111  
golden fried cornbread                 0.027368                 0.092305  
sunset cooler  mocktail                0.051753                 0.070329  
madras curry paste                     1.000000                 0.000000  
cranberry orange scones                0.000000                 1.000000

3.3 Какие рецепты являются наиболее похожими? Прокомментируйте результат (словами).

Чем ближе значение косинусного сходства к единице, тем болшее сходство присутствует между текстами. Соттветственно, наиболее похожими рецептами из выборки `sample` являются `'mermaid delights tuna patties burgers'` и `'molasses pound cake'` (сходство достигает $0,209148$)