# Тема 1.1. Библиотека Numpy

## Самостоятельная работа №1.1 (часть 1)

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np

m = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
print(*m[:5], sep='\n')

[127244     60     16]
[23891    25     7]
[94746    10     6]
[67660     5     6]
[157911     60     14]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
mean_zn_2stolbets = m[:, 1].mean()
mean_zn_3stolbets = m[:, 2].mean()
min_zn_2stolbets = m[:, 1].min()
min_zn_3stolbets = m[:, 2].min()
max_zn_2stolbets = m[:, 1].max()
max_zn_3stolbets = m[:, 2].max()
median_zn_2stolbets = np.median(m[:, 1])
median_zn_3stolbets = np.median(m[:, 2])
print(f'Успешно вычислены: среднее значение 2-ого столбца = {mean_zn_2stolbets} и \
3-его столбца = {mean_zn_3stolbets}, минимум 2-ого столбца = {min_zn_2stolbets} и \
3-его столбца = {min_zn_3stolbets}, максимум 2-ого столбца = {max_zn_2stolbets} и \
3-его столбца = {max_zn_3stolbets}, медианы 2-ого столбца = {median_zn_2stolbets} и \
3-его столбца = {median_zn_3stolbets}.')

Успешно вычислены: среднее значение 2-ого столбца = 21601.00169 и 3-его столбца = 9.05528, минимум 2-ого столбца = 0 и 3-его столбца = 1, максимум 2-ого столбца = 2147483647 и 3-его столбца = 39, медианы 2-ого столбца = 40.0 и 3-его столбца = 9.0.


In [5]:
a = m[:, 1:].mean(axis=0)
a

array([2.16010017e+04, 9.05528000e+00])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [21]:
quant = np.quantile(m[:, 1], 0.75)
print(quant)
x = m[:, 1]
x[x > quant] = quant
m[:, 1] = x

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [6]:
zeros_bool = (m[:, 1] == 0)
print(np.count_nonzero(zeros_bool))
print(zeros_bool)
x = m[:, 1]
x[x == 0] = 1
m[:, 1] = x

479
[False False False ... False False False]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [23]:
print(len(np.unique(m[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [24]:
print(f'Найдено {len(np.unique(m[:, 2]))} вариаций количства ингридиентов: {np.unique(m[:, 2])}')

Найдено 37 вариаций количства ингридиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


## Самостоятельная работа №1.1 (часть 2)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [25]:
m_simple = m[m[:, 2] <= 5]

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [26]:
in_per_min = m[:, 2] / m[:, 1]
print(f'В среднем на одну минуту рецепта приходится {round(in_per_min.mean(), 3)} ингридиентов.')
print(f'Максимальное такое значение = {in_per_min.max()}.')

В среднем на одну минуту рецепта приходится 0.398 ингридиентов.
Максимальное такое значение = 24.0.


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [27]:
top = np.array(sorted(m, key=lambda x: int(x[1])))
top_sto = top[:, 2].mean()

In [28]:
top_sto

9.05528

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [8]:
print(m[np.random.randint(0, len(m), 10)])

[[130015     20      5]
 [132319     65     14]
 [368277     13     12]
 [120964     65      4]
 [132184     65     14]
 [324652     22     10]
 [140185     60      9]
 [102260     55      8]
 [ 46799     40      8]
 [287105     35      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [15]:
sred = m[:, 2].mean()
m_sred = m[m[:, 2] < sred]
print(m_sred.shape[0]*100/m.shape[0])

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [17]:
simple_m = np.append(m, [[0]]*len(m), axis=1)
x = simple_m[:, 1] <= 20
y = simple_m[:, 2] <= 5
simple_m[:, 3] = x*y

13. Выведите процент "простых" рецептов в датасете

In [18]:
c = np.count_nonzero(simple_m[:, 3])
print(c*100/simple_m.shape[0])

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [183]:
short = m[m[:, 1] <= 10]
standart = m[(m[:, 1] < 20)*(m[:, 1] > 10)]
long = m[m[:, 1] >= 20]

max_to_m = min(len(short), len(standart), len(long))
new = np.array([short[:max_to_m], standart[:max_to_m], long[:max_to_m]])

In [186]:
np.shape(new)

(3, 7783, 3)